services:
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: minecraft
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/
      - ./db-init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data: